### ISSUE TITLE
Темы и ссылки в описании эпизода в приложениях для подкастов

### ISSUE THREAD

**Issue by taifen** [InclusivePineapple/inclusivepineapple.github.io#38]
Привет 🙂 Спасибо за замечательные подкаст! 

Было бы здорово видеть темы выпуска и возможность перейти по ссылке при прослушивании в приложениях. Сейчас, к сожалению, есть только короткое описание эпизода

<img width="1800" alt="Screenshot 2024-01-24 at 19 55 18" src="https://github.com/InclusivePineapple/inclusivepineapple.github.io/assets/879100/6f79c40e-65cd-459c-9114-a6ea80859963">

Например, Веб-стандарты:

https://github.com/InclusivePineapple/inclusivepineapple.github.io/assets/879100/fa13ff5f-7e2d-4b3a-aa9a-2ce265ec3b19

**Comment by TatianaFokina** [comment]
> Было бы здорово видеть темы выпуска и возможность перейти по ссылке при прослушивании в приложениях. Сейчас, к сожалению, есть только короткое описание эпизода

Привет, спасибо за предложение! Справедливо. Надо бы допилить наш фид и правда добавить ссылки и таймкоды.
