### ISSUE TITLE
Добавить id к секциям / заголовокам

### ISSUE THREAD

**Issue by glafirazhur** [InclusivePineapple/inclusivepineapple.github.io#8]
Чтобы можно было давать ссылку на конкретный раздел сайта (например, сразу на расшифровку)

**Comment by monochromer** [comment]
Нужна транслитерация или красивые англоязычные названия, то есть для слова "темы" нужно "topics" или "temy"?

**Comment by glafirazhur** [comment]
@monochromer привет! Я за англоязычные названия, т.к. Таня уже использует такой подход в классах :)

**Comment by monochromer** [comment]
Если заголовки меняться не будут, то можно добавлять id на заголовки по такому встроенному в код словарю:
```javascript
{
  'Темы':  'topics',
  'Ссылки к выпуску': 'links',
  'События': 'events',
  'Расшифровка': 'transcription'
}
```
